# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mollom}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan De Poorter"]
  s.date = %q{2010-07-26}
  s.description = %q{Ruby class for easy interfacing with the mollom.com open API for spam detection and content quality assesment.}
  s.email = %q{mollom@openminds.be}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mollom.rb",
     "lib/mollom/api_compatibility.rb",
     "lib/mollom/content_response.rb",
     "mollom.gemspec",
     "pkg/mollom-0.1.1.gem",
     "test/content_response_test.rb",
     "test/mollom_test.rb"
  ]
  s.homepage = %q{http://mollom.rubyforge.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby class for easy interfacing with the mollom.com open API for spam detection and content quality assesment.}
  s.test_files = [
    "test/content_response_test.rb",
     "test/mollom_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

